//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS4_Error_Code_Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS4_Error_Code_Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;CE-30001-4,0x80020001,SCE_KERNEL_ERROR_EPERM,&quot;&quot;許可されていない操作&quot;&quot;,&quot;&quot;Operation not permitted&quot;&quot;,&quot;	
        ///&quot;CE-30002-5,0x80020002,SCE_KERNEL_ERROR_ENOENT,&quot;&quot;そのようなファイル、ディレクトリはない&quot;&quot;,&quot;&quot;No such file or directory&quot;&quot;,&quot;	
        ///&quot;CE-30003-6,0x80020003,SCE_KERNEL_ERROR_ESRCH,&quot;&quot;そのようなプロセスはない&quot;&quot;,&quot;&quot;No such process&quot;&quot;,&quot;	
        ///&quot;CE-30004-7,0x80020004,SCE_KERNEL_ERROR_EINTR,&quot;&quot;システムコールが中断された&quot;&quot;,&quot;&quot;Interrupted system call&quot;&quot;,&quot;	
        ///&quot;CE-30005-8,0x80020005,SCE_KERNEL_ERROR_EIO,&quot;&quot;I/Oエラー&quot;&quot;,&quot;&quot;Input/output error&quot;&quot;,&quot;	
        ///&quot;CE-30006-9,0x80020006,SCE_KERNEL_ERROR_ENXIO,&quot;&quot;デ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Error_Codes {
            get {
                return ResourceManager.GetString("Error_Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader_3_playstation {
            get {
                object obj = ResourceManager.GetObject("loader_3_playstation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playstation_icon {
            get {
                object obj = ResourceManager.GetObject("playstation_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Playstation_Icon1 {
            get {
                object obj = ResourceManager.GetObject("Playstation_Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
